version: "3.9"

services:
  app:
    build: ./app
    container_name: 'app'
    restart: 'always'
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    env_file:
      - './app.env'
  redis:
    image: "redis:alpine"
    container_name: "redis"
  celery:
    build: ./app
    command: celery -A config worker -l INFO
    volumes:
    - ./app:/app
    env_file:
      - './app.env'
    depends_on:
      - app
      - redis